# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: demo-feed
    nugetConfigPath: ./Nuget.config
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
# publish文件上传
- task: PublishBuildArtifacts@1

